In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import mean_absolute_error
from time import process_time
from sklearn import datasets
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict, KFold
from sklearn.preprocessing import StandardScaler

# <font color=black>Linear Discriminant Analysis Feature Selection and Classifiers</font>

In [2]:
df = pd.read_csv('dataset_ros.csv')
dataset = df.copy()
dataset.head()

Destination_Port  Flow_Duration  Total_Fwd_Packets  Total_Backward_Packets  \
0          0.000809   1.475758e-03           0.000009                0.000007   
1          0.000809   1.980333e-04           0.000005                0.000003   
2          0.000809   1.633333e-06           0.000009                0.000007   
3          0.000809   1.208725e-03           0.000005                0.000003   
4          0.861494   2.500000e-08           0.000009                0.000000   

   Total_Length_of_Fwd_Packets  Total_Length_of_Bwd_Packets  \
0                 5.426357e-06                 1.556176e-07   
1                 3.953488e-06                 1.266300e-07   
2                 4.651163e-06                 3.264917e-07   
3                 3.255814e-06                 1.540919e-07   
4                 9.302326e-07                 0.000000e+00   

   Fwd_Packet_Length_Max  Fwd_Packet_Length_Min  Fwd_Packet_Length_Mean  \
0               0.001410               0.015054                0.005891   
1               0.002055               0.021935                0.008585   
2               0.001209               0.012903                0.005050   
3               0.001692               0.018065                0.007070   
4               0.000242               0.002581                0.001010   

   Fwd_Packet_Length_Std  ...  min_seg_size_forward  Active_Mean  Active_Std  \
0                    0.0  ...          3.725292e-08          0.0         0.0   
1                    0.0  ...          5.960467e-08          0.0         0.0   
2                    0.0  ...          3.725292e-08          0.0         0.0   
3                    0.0  ...          3.725292e-08          0.0         0.0   
4                    0.0  ...          3.725292e-08          0.0         0.0   

   Active_Max  Active_Min  Idle_Mean  Idle_Std  Idle_Max  Idle_Min  \
0         0.0         0.0        0.0       0.0       0.0       0.0   
1         0.0         0.0        0.0       0.0       0.0       0.0   
2         0.0         0.0        0.0       0.0       0.0       0.0   
3         0.0         0.0        0.0       0.0       0.0       0.0   
4         0.0         0.0        0.0       0.0       0.0       0.0   

   Label_Category_Num  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 78 columns]

In [3]:
df_x = dataset.iloc[:,:-1]
df_y = dataset.iloc[:,[-1]]

In [4]:
model = RandomForestClassifier()
#model = DecisionTreeClassifier()
#model = GaussianNB()
#model = LogisticRegression()

In [5]:
t1_start = process_time() 
lda = LDA(n_components = None)
pipeline = Pipeline(steps = [('lda', lda), ('model', model)]) 
pipeline.fit(df_x, df_y)
kfold = KFold(n_splits = 10, random_state = 1,shuffle = True)
results = cross_val_score(pipeline, df_x, df_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(pipeline, df_x ,df_y, cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, df_y))
print("Confusion Metrix : \n", confusion_matrix(predict, df_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\pipeline.py:356: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\uti

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\pipeline.py:356: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\pipeline.py:356: DataConversionWarning: A column-vector y was passed wh

Accuracy :  0.9994631776158919
Classification Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00   2014595
           1       1.00      1.00      1.00    907679
           2       1.00      1.00      1.00    565400
           3       1.00      1.00      1.00    463723
           4       1.00      1.00      1.00     50404
           5       0.99      0.94      0.97      6357
           6       1.00      1.00      1.00      8068

    accuracy                           1.00   4016226
   macro avg       1.00      0.99      0.99   4016226
weighted avg       1.00      1.00      1.00   4016226

Confusion Metrix : 
 [[2014364      64      91      10       4      61       1]
 [    455  907213       0      11       0       0       0]
 [    959       2  564439       0       0       0       0]
 [     22       1       0  463700       0       0       0]
 [      4       0       0       0   50400       0       0]
 [    370       0       0     

In [6]:
t1_start = process_time()
model = DecisionTreeClassifier()
pipeline = Pipeline(steps = [('lda', lda), ('model', model)]) 
pipeline.fit(df_x, df_y)
kfold = KFold(n_splits = 10, random_state = 1,shuffle = True)
results = cross_val_score(pipeline, df_x, df_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(pipeline, df_x ,df_y, cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, df_y))
print("Confusion Metrix : \n", confusion_matrix(predict, df_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed w

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


Accuracy :  0.9992492952314029
Classification Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00   2013843
           1       1.00      1.00      1.00    908262
           2       1.00      1.00      1.00    565343
           3       1.00      1.00      1.00    463778
           4       1.00      1.00      1.00     50420
           5       0.99      0.93      0.96      6490
           6       1.00      1.00      1.00      8090

    accuracy                           1.00   4016226
   macro avg       1.00      0.99      0.99   4016226
weighted avg       1.00      1.00      1.00   4016226

Confusion Metrix : 
 [[2013534      84     175       6       1      42       1]
 [   1066  907180       0      16       0       0       0]
 [    988       0  564355       0       0       0       0]
 [     63      16       0  463699       0       0       0]
 [     17       0       0       0   50403       0       0]
 [    484       0       0     

In [9]:
t1_start = process_time() 
model = GaussianNB()
pipeline = Pipeline(steps = [('lda', lda), ('model', model)]) 
pipeline.fit(df_x, df_y)
kfold = KFold(n_splits = 10, random_state = 1,shuffle = True)
results = cross_val_score(pipeline, df_x, df_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(pipeline, df_x ,df_y, cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, df_y))
print("Confusion Metrix : \n", confusion_matrix(predict, df_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\li

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\li

Accuracy :  0.8675355915873102
Classification Report : 
               precision    recall  f1-score   support

           0       0.86      0.97      0.92   1794620
           1       0.93      0.74      0.82   1135644
           2       0.97      0.90      0.94    610865
           3       0.65      0.93      0.77    322831
           4       0.79      0.50      0.61     78881
           5       0.02      0.01      0.01     25359
           6       0.89      0.15      0.25     48026

    accuracy                           0.87   4016226
   macro avg       0.73      0.60      0.62   4016226
weighted avg       0.88      0.87      0.86   4016226

Confusion Metrix : 
 [[1743525   30751    3942     507   10577    4556     762]
 [ 132985  840852     333  161393      18       0      63]
 [  53130    6255  550035      55      47    1343       0]
 [   1277   19734     111  301709       0       0       0]
 [  32240    6791       0       0   39754       0      96]
 [  16539    1980    6634     

In [10]:
t1_start = process_time() 
model = LogisticRegression()
pipeline = Pipeline(steps = [('lda', lda), ('model', model)]) 
pipeline.fit(df_x, df_y)
kfold = KFold(n_splits = 10, random_state = 1,shuffle = True)
results = cross_val_score(pipeline, df_x, df_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(pipeline, df_x ,df_y, cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, df_y))
print("Confusion Metrix : \n", confusion_matrix(predict, df_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: Futur

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-ve

C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\deneysel\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\de

Accuracy :  0.9108598458504794
Classification Report : 
               precision    recall  f1-score   support

           0       0.95      0.90      0.93   2116317
           1       0.81      0.92      0.86    806290
           2       0.99      0.93      0.96    603993
           3       0.92      0.91      0.92    470104
           4       0.28      0.71      0.40     19450
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00        69

    accuracy                           0.91   4016226
   macro avg       0.56      0.62      0.58   4016226
weighted avg       0.92      0.91      0.91   4016226

Confusion Metrix : 
 [[1914468  133641    4181   16606   34806    4551    8064]
 [  48878  738191       0   18817     385      19       0]
 [  40553     608  560148       0    1341    1343       0]
 [   6710   34840     201  428298       0      55       0]
 [   5498       0       0       0   13872      80       0]
 [      3       0       0     